# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  
steps:
- checkout: self
  submodules: recursive
  
- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)"'
    restoreKeys: gradle
    path: $(GRADLE_USER_HOME)
  displayName: Gradle Build Cache
  
- task: Gradle@2
  displayName: 'Gradle build : Android Library'
  inputs:
    gradleOptions: '-Xmx3072m'
    
- script: 'gradlew --stop'    
  displayName: Stop Gradle Daemon